services:
  backend:
    build:
      context: ./backend
    container_name: my-backend
    ports:
      - "6000:6000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    
#   frontend:
#     build:
#       context: ./frontend
#       args:
#         - VITE_API_BASE_URL=http://localhost:6000
#     container_name: my-frontend
#     ports:
#       - "8080:80"
#     depends_on:
#       - backend
#     # environment:
#     #   - VITE_API_BASE_URL=http://my-backend:6000
#     networks:
#       - my-network

# networks:
#   my-network:
