services:
  frontend:
    build:
      context: ./frontend
      args:
        # Using the public URL since requests will go through nginx
        - VITE_API_BASE_URL=https://photobook.kilometers.ai/api
    container_name: my-frontend
    networks:
      - app-network
    ports:
      - "3000:80" # This port will only be used by nginx on the host

  backend:
    build:
      context: ./backend
      args:
        - DATABASE_URL=${DATABASE_URL}
        - NODE_ENV=${NODE_ENV}
    container_name: my-backend
    ports:
      - "6000:5004"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      # - POSTGRES_USER=${POSTGRES_USER}
      # - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=my-database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
#   frontend:
#     build:
#       context: ./frontend
#       args:
#         - VITE_API_BASE_URL=http://localhost:6000
#     container_name: my-frontend
#     ports:
#       - "8080:80"
#     depends_on:
#       - backend
#     # environment:
#     #   - VITE_API_BASE_URL=http://my-backend:6000
#     networks:
#       - my-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
