@PhotoFinderAPI_HostAddress = http://localhost:5015

GET {{PhotoFinderAPI_HostAddress}}/api/photographers
Accept: application/json

###

GET {{PhotoFinderAPI_HostAddress}}/api/photographers/1

###

GET {{PhotoFinderAPI_HostAddress}}/api/photographers/999

### Create a new photographer

POST http://localhost:5015/api/photographers
Content-Type: application/json

{
  "name": "Alex Rivera",
  "style": "Street",
  "location": "Austin, TX",
  "bio": "Captures urban life in motion",
  "rating": 4.7
}

### 

PUT http://localhost:5015/api/photographers/1
Content-Type: application/json

{
  "name": "Nick Updated",
  "style": "Street",
  "location": "Atlanta",
  "bio": "Updated bio",
  "rating": 4.9
}

###

DELETE http://localhost:5015/api/photographers/3

###

DELETE http://localhost:5015/api/photographers/999