name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build application
        run: npm run build

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: photography_test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Setup test environment
        run: |
          cp .env.example .env.test || echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/photography_test_db" > .env.test
          echo "NODE_ENV=test" >> .env.test
          echo "JWT_SECRET=test_secret" >> .env.test

      - name: Run database migrations
        run: |
          npx prisma generate
          npx prisma migrate deploy
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/photography_test_db

      - name: Run tests
        run: npm test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/photography_test_db

  e2e:
    runs-on: ubuntu-latest
    needs: [frontend, backend]

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: photography_e2e_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install root dependencies
        run: npm ci

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Setup E2E environment
        run: |
          cp .env.e2e .env || echo "NODE_ENV=test" > .env
          echo "VITE_API_BASE_URL=http://localhost:5002" >> .env
          echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/photography_e2e_db" >> .env
          echo "JWT_SECRET=e2e_test_secret" >> .env
          echo "JWT_EXPIRES_IN=7d" >> .env

      - name: Setup backend E2E environment
        working-directory: ./backend
        run: |
          echo "NODE_ENV=test" > .env.test
          echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/photography_e2e_db" >> .env.test
          echo "JWT_SECRET=e2e_test_secret" >> .env.test
          echo "PORT=5002" >> .env.test

      - name: Run database migrations
        working-directory: ./backend
        run: |
          npx prisma generate
          npx prisma migrate deploy
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/photography_e2e_db

      - name: Seed E2E database
        working-directory: ./backend
        run: npx prisma db seed
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/photography_e2e_db

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Run E2E tests
        run: npx playwright test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/photography_e2e_db

      - name: Upload E2E test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-test-results
          path: |
            e2e-results/
            test-results/
          retention-days: 30

      - name: Upload E2E test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-html-report
          path: e2e-results/html-report/
          retention-days: 30